### ISSUE TITLE
Don't propagate NaN for {f32,f64}::{min,max}

### ISSUE THREAD

**Issue by bjorn3** [bjorn3/rustc_codegen_cranelift#1049]
libstd docs for {f32,f64}::{min,max}:

> If one of the arguments is NaN, then the other argument is returned.

Blocked on https://github.com/bytecodealliance/wasmtime/issues/1906

**Comment by eggyal** [comment]
Perhaps Rust's behaviour is wrong and cg_clif is already doing the right thing.  See https://github.com/rust-lang/rust/issues/83984

**Comment by sunfishcode** [comment]
Rust+llvm are following the family of functions known in IEEE 754-2008 as `minNum` which prefer a number over a NaN and don't define what happens between `-0.0` and `+0.0` (and has surprising behavior on sNaN).

Cranelift's `fmin` follows IEEE 754-2019's new `minimum` and WebAssembly's `min`, which prefer a NaN over a number and treat `-0.0` as less than `+0.0` (and have unsurprising behavior on sNaN).

IEEE 754-2019 also defines `minimumNumber`, which prefers a number over a NaN and treats `-0.0` as less than `+0.0` (and has unsurprising behavior on sNaN). WebAssembly's MVP was designed before IEEE 754-2019's direction on this issue was known, so it didn't originally add operators for `minimumNumber` and `maximumNumber`. Now that IEEE 754-2019 is published, it's a reasonable assumption that WebAssembly should eventually add operators for these.
