### ISSUE TITLE
How to Use JIT

### ISSUE THREAD

**Issue by theduke** [bjorn3/rustc_codegen_cranelift#1192]
`usage.md` mentions that the JIT mode requires certain dynamic libraries, but it doesn't specify which ones or how to set them up.

Trying to run jit/lazy-jit results in a bunch of linker errors for me.

The error messages refer to libc items.

```
  = note: ld.lld: error: /home/theduke/dev/github.com/bjorn3/rustc_codegen_cranelift/build/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-64ad50e1415b1d9b.so: undefined reference to stat64@GLIBC_2.33 [--no-allow-shlib-undefined]
          ld.lld: error: /home/theduke/dev/github.com/bjorn3/rustc_codegen_cranelift/build/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-64ad50e1415b1d9b.so: undefined reference to fstat64@GLIBC_2.33 [--no-allow-shlib-undefined]
          ld.lld: error: /home/theduke/dev/github.com/bjorn3/rustc_codegen_cranelift/build/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-64ad50e1415b1d9b.so: undefined reference to lstat64@GLIBC_2.33 [--no-allow-shlib-undefined]
          ld.lld: error: /home/theduke/dev/github.com/bjorn3/rustc_codegen_cranelift/build/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-64ad50e1415b1d9b.so: undefined reference to fstatat64@GLIBC_2.33 [--no-allow-shlib-undefined]
          collect2: error: ld returned 1 exit status
```

[log.txt](https://github.com/bjorn3/rustc_codegen_cranelift/files/6951382/log.txt)

**Comment by bjorn3** [comment]
Does `RUSTFLAGS="-Cprefer-dynamic" /path/to/cg_clif/build/cargo build` work? That is without using jit mode. This error happens during compilation of a build script way before the jit mode actually gets to run. Which glibc version do you have? Did you build cg_clif in an environment with a newer glibc version than you are building your project? (Maybe because of a container, or nix or something like that?)

> usage.md mentions that the JIT mode requires certain dynamic libraries, but it doesn't specify which ones or how to set them up.

You did have to add a new dependency with

```toml
[lib]
crate-types = ["dylib"]
```

to your executable. This dylib needs to depend on all crates your executable depends on and needs to reference them from `lib.rs`. (`use my_dep;` is enough) Finally you need to reference this dylib from `main.rs` just like the dylib references the dependencies.

I know this is pretty hard to setup and I hope to be able to make it easier in the future, but the jit mode is not a high prioritt to me right now. It is more of a proof of concept than something very usable. For this reason the cg_clif version that will (hopefully) soon be distributed as rustup component will have the jit mode disabled.

**It may not be worth your time to try to get it working.** As of right now at least the non-lazy version is probably slower than not jitting. None of the jit modes support incremental compilation as they exit the process before the incr comp cache is finalized and because no object files are produced that can be cached.

**Comment by bjorn3** [comment]
> It may not be worth your time to try to get it working.

I think I will update the documentation tomorrow.

**Comment by theduke** [comment]
Understood. 

I was primarily interested in testing out how much the lazy JIT can speed up development.
But considering the constraints, it seems like that's not really viable at the moment.

**Comment by bjorn3** [comment]
Updated the docs.
