### ISSUE TITLE
[need verification on a statement]: panic does segfault (Aborted core dumped) by default cuz its not yet supported

### ISSUE THREAD

**Issue by alexzanderr** [bjorn3/rustc_codegen_cranelift#1336]
hello

im getting a panic inside my project from the crates that im using.

by running in terminal this happened:
- program prints panic message
- it does some stuff because 1 core is up and running and linux system core-dump writes some logs or does some stuff (i dont know exactly, i saw it was using the disk and i saw the process on htop)
- and then if i dont force close the GUI app (my project) the system aborts automatically showing in the terminal `Aborted (core dumped)`

i've saw this in the readme
```
Unwinding on panics (https://github.com/bytecodealliance/wasmtime/issues/1677, -Cpanic=abort is enabled by default)
```
and also saw that cleanup is requested as an open issue and its still open so no cleanup right now.

so my guess is that cranelift compiles code with panic=abort by default both in debug and release mode. right?

and when the rust program panics with panic=abort it will create a segfault. right? (this is what i saw in the past when running a release binary with panic=abort)

this is expected to happen right? im assuming, but i need your confirmation.

thanks in advance.

**Comment by bjorn3** [comment]
Yes, panics do indeed abort (SIGABRT) due to `-Cpanic=abort` being the only mode supported by cg_clif. Note that this is not a segfault (SIGSEGV), but a controlled `abort()` call. Both do indeed write core dumps by default on some distros. Depending on the amount of memory the process used, this can take a while. If you want to disable core dumping, you should be able to run `ulimit -c 0` in the terminal from which you run the compiled program. This will only apply to processes spawned from this specific terminal and won't persist once you close it.

**Comment by alexzanderr** [comment]
wow, very nice guide. thanks a lot.

**Comment by bjorn3** [comment]
I believe I answered your question. If not, feel free ask more though.

**Comment by alexzanderr** [comment]
ok, i can confirm that both ways are achieving the same result.

and indeed, i can confirm that is working (`ulimit -c 0`), the program is not writing core-dumps anymore into the system, so right now the process closes immediately.

thanks a lot for the response!

**Comment by bjorn3** [comment]
The second one definitively works. The first one may or may not work. ulimit is a command built into your shell which changes the "resource limits" of the shell itself, any processes started by the shell then inherit these "resource limits".
