### ISSUE TITLE
Consider enabling "Releases" on GitHub

### ISSUE THREAD

**Issue by peter-kehl** [bjorn3/rustc_codegen_cranelift#1337]
Hi. Looking forward to using Cranelift target with Rust.

Could you consider enabling "Releases" tab on GitHub? That would allow people to Subscribe > Customize, so that once this is public-ready, they would get notified.

Even if (later) you choose not to use Releases (and use CI instead, as per now: https://github.com/bjorn3/rustc_codegen_cranelift/issues/1210#issuecomment-984636603), you could publish a dummy release instructing people where/how to download/install it.

Thank you either way. Happy New Year.

For readers: If we don't have "Releases", you could subscribe to [distributing cg_clif with rustup](https://github.com/rust-lang/rust/pull/81746), which is closely related to getting this public-ready.

**Comment by bjorn3** [comment]
I don't think there is much value in this for cg_clif. For the use case of downloading a pre-compiled version, the artifacts produced during CI should suffice. For the use case of knowing when to update, I don't think releases add much right now. Improvements happen mostly incrementally rather than as a big change all at once. There is also no stability difference between a concrete release and the current master branch. In the future the plan is to add cg_clif as a rustup component such that you can use the version of cg_clif corresponding with the rustc nightly you use.

**Comment by jeffparsons** [comment]
> In the future the plan is to add cg_clif as a rustup component such that you can use the version of cg_clif corresponding with the rustc nightly you use.

At the risk of this coming across as "are we there yet"...

Can I ask what have been the main challenges in landing this? I noticed today that the PR has been open for nearly two years — quite the marathon!

**Comment by bjorn3** [comment]
It's been going slower than I did like. The main blockers are listed in https://github.com/bjorn3/rustc_codegen_cranelift/milestone/2. Of these testing cg_clif in rust's CI is the most important (https://github.com/bjorn3/rustc_codegen_cranelift/issues/1290). Over the past couple of months I have slowly been working on making cg_clif's test suite suitable for running in rust's CI. Once that is done I need to wait for https://github.com/rust-lang/rust/pull/105977 to land to fix cg_clif again. After that I don't think it would be too much work to wire it up on rust's side.
